apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-report-service
  labels:
    app: medical-report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-report-service
  template:
    metadata:
      labels:
        app: medical-report-service
    spec:
      containers:
      - name: medical-report-service
        image: shuvankar/medical-report-service:v2.0
        imagePullPolicy: Never
        
---
apiVersion: v1
kind: Service
metadata:
  name: medical-report-service
spec:
  type: NodePort
  selector:
    app: medical-report-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000